#!/usr/bin/python3
"""
Tests cases for the add_integer function.
"""


from ..0-add_integer import add_integer
#Test with two integers
>>> add_integer(1, 2)
3

#Test with positive integer and negative integer
>>> add_integer(100, -2)
98

#Test with one integer
>>> add_integer(2)
100

#Test with float and negative integer
>>> add_integer(100.3, -2)
98

# Test with two floats
>>> add_integer(4.5, 5.5)
9

#Test with non-integer or float parameters
>>> add_integer(4, "School")
Traceback (most recent call last):
    ...
TypeError: b must be an integer

#Test with a None parameter
>>> add_integer(None)
Traceback (most recent call last):
    ...
TypeError: a must be an integer or b must be an integer
