#!/usr/bin/python3
"""
Tests cases for the add_integer function.
"""
def add_integer(a, b=98):
    """
    Add two integers

    Parameter:
    - a (int): The first integer to be added.
    - b (int, optional): The second integer to be added. Defaults to 98 if not provided.

    Returns:
    int: The sum of the two integers, `a` and `b`.
    example:
    #Test with two integer
    >>> add_integer(1, 2)
    3

    #Test with positive integer and negative integer
    >>> add_integer(100, -2)
    98

   #Test with one integer
    >>> add_integer(2)
    100

    #Test with float and negative integer
    >>> add_integer(100.3, -2)
    98

    # Test with two floats
    >>> add_integer(4.5, 5.5)
    9

    #Test with non-integer or float parameters
    >>> add_integer(4, "School")
    Traceback (most recent call last):
        ...
    TypeError: b must be an integer

    #Test with a None parameter
    >>> add_integer(None)
    Traceback (most recent call last):
        ...
    TypeError: a must be an integer or b must be an integer
    """
    return a + b

if __name__ == "__main__":
    import doctest
    doctest.testmod(verbose=True)
